update content and add deployment github action
RENCI/star-website pull request #59
Opened 2024-08-08 14:45 UTC by suejinkim20

2024-08-08 15:00 UTC, mbwatson requested changes
:+1: looks good!

please clean up those eslint warnings :grin:

2024-08-12 16:19 UTC, mbwatson requested changes
i see a few eslint warnings
- Warning: React does not recognize the `backgroundColor` prop on a DOM element
- Warning: Each child in a list should have a unique "key" prop
- warning  'rows' is assigned a value but never used  no-unused-vars

2024-08-12 16:19 UTC, mbwatson commented on src/components/dates-table.js
> +console.log(datesArray)
can probably lose this log

2024-08-12 18:25 UTC, suejinkim20 commented
> i see a few eslint warnings
> 
> * Warning: React does not recognize the `backgroundColor` prop on a DOM element
> * Warning: Each child in a list should have a unique "key" prop
> * warning  'rows' is assigned a value but never used  no-unused-vars

hi @mbwatson ! 

i've removed the two console.logs and addressed the remaining browser warnings.

there are two remaining eslint warnings that are both related to future utilization of the Monday plugin for Dates. these errors should disappear when i implement the logic to pull in the dates from the Monday board rather than the current hardcoded method. the two errors are as follows:

```
/star-website/src/components/sections/important-dates.js
 7:9  warning  'rows' is assigned a value but never used  no-unused-vars
```
  
```
 /star-website/src/components/sections/programs/starShipPanel.js
 30:9  warning  'data' is assigned a value but never used  no-unused-vars
```

please let me know if there are any other errors i missed. thank you!

2024-08-12 18:31 UTC, mbwatson approved these changes
:+1:

2024-08-12 19:00 UTC, merged